### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by DeKleineKobini** [Suwayomi/Suwayomi-VUI#126]
It would be great to have the docker image support arm64.

**Comment by DeKleineKobini** [comment]
Since oven/bun is used, the image itself might already work but just need to be uploaded. I'll see if I can build the docker image with the existing Dockerfile on my arm system.

**Comment by Robonau** [comment]
it now supports all the os/arch that the nginx-unprivileged image does
`linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64, linux/386, linux/ppc64le, linux/s390x`
