### ISSUE TITLE
[Tracking Feature Addition] Integrating Kitsu as a tracker in VUI

### ISSUE THREAD

**Issue by pokewizardSAM** [Suwayomi/Suwayomi-VUI#143]
As far i have tested this webui skin , it's pretty good and has a lots of good features too. The most impressive was tracking feature, i personally have a lot's of devices so the feature is very usefull for me.
It's just that it doesnt support kitsu yet , which like has my 70% of the manga tracked. i would love to see thing being implemented.

Thanks to the person who made this

**Comment by Robonau** [comment]
VUI is just the first UI to implement the servers tracking endpoints, itl be coming in the webui soon and the others later

the addition of Kitsu would be a server change not a VUI change
feel free to request it in an [issue](https://github.com/Suwayomi/Suwayomi-Server/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=%5BFeature+Request%5D+%3Cshort+description%3E) in the suwayomi-server repo (though you might have better luck asking in the [discord](https://discord.gg/DDZdqZWaHA))
