### ISSUE TITLE
Showing the details of a Manga not possible

### ISSUE THREAD

**Issue by Trauer** [Suwayomi/Suwayomi-VUI#253]
client version
VUI-r1236
Server version
v1.1.1-r1649

After clicking a manga I only get a empty screen with loading text.
![grafik](https://github.com/user-attachments/assets/6b2bdf64-923a-48dd-91ff-53f3da8b6e4b)
![grafik](https://github.com/user-attachments/assets/6f44e7e3-b720-4d7e-afc0-287f9bad94a0)

I get this problem for all manga sources and all mangas

If I switch to WebUI its possible to open the mangas normally so I think its related to VUI

**Comment by Robonau** [comment]
i can't reproduce the issue

**Comment by Trauer** [comment]
Hi, with 
client version
VUI-r1239
its working again!

**Comment by sezaru** [comment]
Why is this closed? it still happens with the latest version with Firefox.

Here is the error in console:

![Image](https://github.com/user-attachments/assets/1adeb174-63b1-49d6-9b8e-13bc0605f415)
