### ISSUE TITLE
2 main issues i have with VUI

### ISSUE THREAD

**Issue by maybeanuser1** [Suwayomi/Suwayomi-VUI#254]
### **1.(Scrolling)**
when using Pg+ or Pg- , arrow keys , space bar the screen freezes and slowly goes up or down.

### **2.(Global search)** 
when using Global search all the filters that don't show any results don't go down in the list and take up space.

**Comment by Robonau** [comment]
1. i my experience this only happens when there are allot of pages already open (like 50 chapters in)
there is nothing i can do about it, its already doing the keybind and scroll as efficiently as possible

2. this is intentional, i don't like how it moves in mihon
